import { Backdrop, Toast } from "components";
import { ColorVariant } from "interfaces/Color";
import type { NextPage } from "next";
import Head from "next/head";
import { Fragment } from "react";
import { useDispatch, useSelector } from "react-redux";
import { clearMessage } from "redux/actions/uiActions";
import { UiState } from "redux/reducers/uiReducer";
import { RootState } from "redux/store";
import { FormShipment } from "views";

const Home: NextPage = () => {
  const { loading, message } = useSelector<RootState, UiState>(({ ui }) => ui);
  const dispatch = useDispatch();

  const handleOnClose = () => {
    dispatch(clearMessage());
  };

  return (
    <Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Backdrop open={loading} />
        <Toast
          variant={message?.variant as ColorVariant}
          // delay={3000}
          open={Boolean(message)}
          onClose={handleOnClose}
        >
          {message?.text}
        </Toast>
        <FormShipment />
      </main>
      <footer></footer>
    </Fragment>
  );
};

export default Home;
