import Button from "components/Button";
import Input from "components/Input";
import type { NextPage } from "next";
import Head from "next/head";
import { FormShipment } from "views";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <FormShipment />
      </main>
      <footer></footer>
    </div>
  );
};

export default Home;
